version: "3.8"

services:
  myjenkins:
    container_name: my_custom_jenkins
    image: jenkins/jenkins:lts
    user: root
    environment:
     #MY_NAME: "santi_devops"
      # Gmail extra configuration for mailer plugin
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      SONARQUBE_HOST:  #Nombre del servicio
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Named  Docker volume details at the bottom
      - jenkins_home:/var/jenkins_home
      # WARNING:
      - /var/run/docker.sock:/var/run/docker.sock
    #restart: always
    networks:
      - net_devops
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
  mysonarqube:
    container_name: my_custom_sonarqube
    # build: ./sonarqube_home
    #image: sonarqube:7.9.5-community
    image: mc1arke/sonarqube-with-community-branch-plugin:latest
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      #SONARQUBE_USERNAME: admin
      #SONARQUBE_PASSWORD: prueba8080
    ports:
      - "9000:9000"
    networks:
      - net_devops
    volumes:
       #- ./sonarqube_home/conf/:/opt/sonarqube/conf
       #- ./sonarqube_home/data/:/opt/sonarqube/data
      # - ./sonarqube_home/logs/:/opt/sonarqube/logs
      # - ./sonarqube_home/extensions/:/opt/sonarqube/extensions
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions 
    restart: unless-stopped
    # restart: always
    deploy:
      resources:
         limits:
           cpus: "2"
           memory: 3G


volumes:
  jenkins_home:
    name: "custom_jenkins_home"
  sonarqube_conf:
    name: "custom_sonarqube_conf"
  sonarqube_data:
   name: "custom_sonarqube_data"
  sonarqube_extensions:
    name: "custom_sonarqube_extensions"
networks:
  net_devops:
    driver: bridge
    name: net_devops
