

def qualityGateValidation(qg) {
  if (qg.status != 'OK') {
    return true
  }
  return false
}
pipeline {
  agent any //Usa cualquier agente en el pipeline 

  tools { // para todo el proceso se usa la herramienta de nodeJS, forma de usar el plugin de nodeJs (de jenkins), en jenkinsfile
      nodejs 'nodejs'
  }

  environment {//
      PROJECT_ROOT = 'express-mysql/app'// hace referencia a donde se encuentra el root del proyecto, es donde esta la aplicacion
      REGISTRY = 'cesarbv/docker-pirate-express'
      /*
      ESTRUCTURA DE LAS IMAGENES EN SU NOMBRE 
        RegistryName/folderName/NFolderName/imageName:tag
      */
  }

  stages {
      stage('Hello') { //Imprime mensajes para ver si jenkins file funca
        steps {
          // First stage is a sample hello-world step to verify correct Jenkins Pipeline
          echo 'Hello World, I am Happy'
          echo 'This is my amazing Pipeline'
        }
      }
      stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cesarbv22/docker-pirate']]])
             }
      }
      stage('Install dependencies') {//acá se configuran las dependencias de nodeJs
        steps {
          sh 'npm --version'
          sh "cd ${PROJECT_ROOT}; npm install" //nos dirigimos a la ruta del proyecto y ahi se corre el npm install
        }
      }
      stage('Unit tests') {// dos dirigimos a la ruta del proyecto y ahi ejecutamos las pruebas unitarias 
        steps {
          // Run unit tests
          sh "cd ${PROJECT_ROOT}; npm run test"
        }
      }
      stage('Generate coverage report') {
        steps {
          sh "cd ${PROJECT_ROOT}; npm run coverage"
        }
      }
      stage('scan') {
          environment {//variable de entorno
            // Previously defined in the Jenkins "Global Tool Configuration"
            scannerHome = tool 'sonar-scanner' //sonar-scanner es el nombre que se puso cuando se configuró el plugin en jenkins
          }
          steps {
            // "sonarqube" is the server configured in "Configure System"
            withSonarQubeEnv('sonarqube') {// sonarqube, es el nombre del sonarqube server que se configuró
             echo 'ESCANER' 
              // sh "${scannerHome}/bin/sonar-scanner \
              //             -Dsonar.projectKey=SimpleExpressExample:Test \
              //             -Dsonar.projectName=SimpleExpressExample \
              //             -Dsonar.projectVersion=0.0.${BUILD_NUMBER} \
              //             -Dsonar.host.url=http://mysonarqube:8888 \
              //             -Dsonar.sources=./${PROJECT_ROOT}/app.js,./${PROJECT_ROOT}/config/db.config.js,./${PROJECT_ROOT}/routes/developers.js \
              //             -Dsonar.login=admin \
              //             -Dsonar.password=prueba8080 \
              //             -Dsonar.tests=./${PROJECT_ROOT}/test \
              //             -Dsonar.javascript.lcov.reportPaths=./${PROJECT_ROOT}/coverage/lcov.info"
            }
            timeout(time: 3, unit: 'MINUTES') {
              // In case of SonarQube failure or direct timeout exceed, stop Pipeline
              waitForQualityGate abortPipeline: qualityGateValidation(waitForQualityGate())
            }
          }
      }
      stage('Build docker-image') { //empaquetar la aplicacion en el path especifico
        steps {
           //sh "cd ./${PROJECT_ROOT};docker build -t ${REGISTRY}:${BUILD_NUMBER} . "
          echo 'construir imagen con docker'
        }
      }
      stage('Deploy docker-image') {
        steps {
          // // If the Dockerhub authentication stopped, do it again
            //sh 'docker login'
            //sh "docker push ${REGISTRY}:${BUILD_NUMBER}"
             echo 'despliegue'
        }
      }
  }
}

