@Library("shared-library") _ //Importanción de la librería compartida, definida en las configuraciones de Jenkins
def qualityGateValidation(qg) {
  if (qg.status != 'OK') {
    // emailext body: "WARNING SANTI: Code coverage is lower than 80% in Pipeline ${BUILD_NUMBER}", subject: 'Error Sonar Scan,   Quality Gate', to: "${EMAIL_ADDRESS}"
    return true
  }
  // emailext body: "CONGRATS SANTI: Code coverage is higher than 80%  in Pipeline ${BUILD_NUMBER} - SUCCESS", subject: 'Info - Correct Pipeline', to: "${EMAIL_ADDRESS}"
  return false
}
pipeline{
    agent any

    tools{
        nodejs 'nodejs'
    }//forma de utilizar el plugin de nodeJs en el pipeline. Este nombre 'nodejs' es el configurado en jenkins

    environment {
      PROJECT_ROOT = 'express-mysql/app' 
      REGISTRY = 'cesarbv/docker-pirate-express' 
      DOCKERHUB_CREDENTIALS = credentials('cesarbv-dockerhub')
      
    }
    /*   ESTRUCTURA DE LAS IMAGENES EN SU NOMBRE 
      RegistryName/folderName/NFolderName/imageName:tag
    */ 

    stages{ // stage 1 de ejemplo

    
        stage('Test :D'){
            steps {
                  echo "Test"
              helloworld(day:"lunes",name:"Marshall")
            }
        }

         stage('Connection Test Hello Def'){
            steps {
                echo "Test"
              hello()
            }
        }

        stage('Checkout'){
            steps{
                  echo "Test"
              checkProject()
            }
        }

        stage('Install Dependencies'){
            steps{
              echo "${PROJECT_ROOT} Instalar dependencias"
              installDependencies(project_root: PROJECT_ROOT)
            }
        }

         stage('Unit test'){
            steps{
                unitTest(project_root: PROJECT_ROOT)
                echo "${PROJECT_ROOT} Pruebas unitarias"
            }
        }

         stage('Generate coverage report'){
            steps{
                coverageProject(project_root: PROJECT_ROOT)
                echo "${PROJECT_ROOT} Run coverage"
            }
        }

         stage('Scan'){
             environment {//variable de entorno
                scannerHome = tool 'sonar-scanner' //sonar-scanner es el nombre que se puso cuando se configuró el plugin en jenkins
            }
            steps{
                withSonarQubeEnv('sonarqube') {
                    echo "Paso del scan"
                    escaneo(homeScanner:"${scannerHome}",buildNumber:"${BUILD_NUMBER}",project_root: "${PROJECT_ROOT}" )
                }
                timeout(time: 3, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: qualityGateValidation(waitForQualityGate())
                }
                
            }
        }

        stage('Build Docker-image'){
            steps{// ya se usa el access token generado con docker-hub y administrado ahora en jenkins
                proyectBuild(project_root:"${PROJECT_ROOT}",registry:"${REGISTRY}",buildNumber:"${BUILD_NUMBER}")
                echo "${PROJECT_ROOT}-- ${REGISTRY}-- ${BUILD_NUMBER} CONSTRUIR LA IMAGEN"
            }
        }
        stage('Deploy Docker-image'){
            steps{
                deployProject(registry:"${REGISTRY}",build_number:"${BUILD_NUMBER}")
                echo "${PROJECT_ROOT}-- ${REGISTRY}-- ${BUILD_NUMBER} PULL IMAGEN"
            }
        } 

        stage ('Image Deploy in my Premise- TEST'){
            steps{
                echo "Prueba crear container en pipeline"
               // createContainer(name:"pl-cnt-${BUILD_NUMBER}",registry:"${REGISTRY}",build_number:"${BUILD_NUMBER}")
                //sh "docker run -it -d -p 3001:3000 --name plTest cesarbv/docker-pirate-express:46"
                sh "docker run -it --rm -p 3001:3000 --name pl-cnt ${REGISTRY}:${BUILD_NUMBER}"
            }
        }       
    }
}
/*
docker run -it -d -p 3001:3000 --name prueba-corregida 1e249
docker run -it -d -p 3001:3000 --name TESTO cesarbv/docker-pirate-express:46
*/

